apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mongoexpress-deployment
  labels:
    app: my-mongoexpress-app
spec:
  selector:
    matchLabels:
      app: my-mongoexpress-app
  replicas: 2
  template:
    metadata:
      labels:
        app: my-mongoexpress-app
    spec:
      containers:
        - name: mongoexpress
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: my-mongo-secret
                  key: root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-mongo-secret
                  key: root-password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: my-mongo-configmap
                  key: mongo-server-url
---
apiVersion: v1
kind: Service
metadata:
  name: my-mongoexpress-service
spec:
  selector:
    app: my-mongoexpress-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000