apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mongo-deployment
  labels:
    app: my-mongo-app
spec:
  selector:
    matchLabels:
      app: my-mongo-app
  replicas: 2
  template:
    metadata:
      labels:
        app: my-mongo-app
    spec:
      containers:
        - name: my-mongo-app
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-mongo-secret
                  key: root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-mongo-secret
                  key: root-password
---
apiVersion: v1
kind: Service
metadata:
  name: my-mongo-service
spec:
  selector:
    app: my-mongo-app
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017